### PR TITLE
fix responsive product project page

### PR DESCRIPTION
**Pull request by hoaithanh23399**

### CODE REVIEW

**Comment by hoaithanh23399** [comment]
**Resuts**

**Comment by hoaithanh23399** [comment]
https://github.com/user-attachments/assets/543a8279-ba5f-48cc-83c0-c82c47413aca

**Comment by hoaithanh23399** [comment]
https://github.com/user-attachments/assets/18b6aa60-9795-4517-94dc-f1cab3261821

**Comment by hoaithanh99** [comment]
https://github.com/user-attachments/assets/02741a7c-4d2e-4c1d-a101-556d1480165f

**Comment by hoaithanh99** [comment]
https://github.com/user-attachments/assets/af5b4050-737b-4e46-b38b-54112d4d078a

**Review by chinhvuquang — APPROVED** [review]

**Pull request merged**
